name: CustomMessages
version: 1.0.3
main: org.garsooon.custommessages.CustomMessages
author: Garsooon

commands:
  setjoin:
    description: Set your custom join message
    usage: /<command> <message>
    aliases: [cjm, sjm, setgreeting]
    permission: custommessages.setjoin
  setleave:
    description: Set your custom leave message
    usage: /<command> <message>
    aliases: [clm, slm]
    permission: custommessages.setleave
  viewmessages:
    description: View a player's custom messages
    usage: /<command> <player>
    aliases: [vjm, vlm]
    permission: custommessages.admin
  setplayerjoin:
    description: Set another player's join message
    usage: /<command> <player> <message>
    aliases: [fcjm]
    permission: custommessages.admin
  setplayerleave:
    description: Set another player's leave message
    usage: /<command> <player> <message>
    aliases: [fclm]
    permission: custommessages.admin
  resetmessages:
    description: Reset a player's custom messages
    usage: /<command> <player>
    aliases: [rcjm, rclm]
    permission: custommessages.admin

permissions:
  custommessages.setjoin:
    description: Allows setting custom join message
    default: op
  custommessages.setleave:
    description: Allows setting custom leave message
    default: op
  custommessages.admin:
    description: Allows modifying other players' messages
    default: op